apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyterhub-derek-deployment
  name: jupyterhub-service
  namespace: default
spec:
  ports:
  - name: 8000-to-8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: jupyterhub-derek-deployment
  type: ClusterIP